// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotationApi.Models;

namespace QuotationApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200529155740_InsertRequired")]
    partial class InsertRequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("QuotationApi.Models.Quotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotationText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Aziz",
                            PubDate = new DateTime(2020, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuotationText = "Да прибудет с тобой сила, мой юный падаван"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Khurshed",
                            PubDate = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuotationText = "Не надо мелочиться, нужно рубить с корня"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Firdavs",
                            PubDate = new DateTime(2020, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuotationText = "Французишь друг мой"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Shahzod",
                            PubDate = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuotationText = "Kali лучше чем parrot"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Amin",
                            PubDate = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuotationText = "Много поколений процессоров не бывает"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
